name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api'
  AZURE_WEB_APP_PACKAGE_PATH: './app'
  NODE_VERSION: '18.x'

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prod_deploy_infra:
    runs-on: ubuntu-latest
    name: Deploy Infrastructure
    environment: production
    outputs:      
      function_app_name: ${{ steps.deploy_infra.outputs.function_app_name }}
      function_app_url: ${{ steps.deploy_infra.outputs.function_app_url }}
      logic_app_name: ${{ steps.deploy_infra.outputs.logic_app_name }}
      web_app_name: ${{ steps.deploy_infra.outputs.web_app_name }}
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4.1.1

    - name: Login via Az module
      uses: azure/login@v2.1.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
        enable-AzPSSession: true 

    - uses: Azure/CLI@v2
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ vars.RG_NAME }} --location ${{ vars.RG_LOCATION }}
          echo "Azure resource group created"                 

    - name: Deploy Infrastructure
      id: deploy_infra
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.RG_NAME }}
        template: ./infra/main.bicep
        parameters: 'poc_name=${{ vars.POC_NAME }} azure_devops_pat=${{ secrets.AZURE_DEVOPS_PAT }}'
        failOnStdErr: false
        deploymentName: 'deploy-infra-${{ github.run_id }}'
        scope: 'resourcegroup'      
  
  prod_build_and_deploy_function:
    runs-on: ubuntu-latest
    name: Build and Deploy Function App
    needs: [prod_deploy_infra]
    environment: production
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4.1.1

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v4.0.1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build --if-present
        npm run test --if-present
        popd

    - name: Login via Az module
      uses: azure/login@v2.1.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
        enable-AzPSSession: true 
    
    - name: Get publish Profile
      id: funcpublishprofile
      uses: azure/powershell@v2
      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{ vars.RG_NAME }} `
              -Name ${{ needs.prod_deploy_infra.outputs.function_app_name }}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest

    - name: Deploy Function App
      uses: Azure/functions-action@v1.5.1
      with:
        app-name: ${{ needs.prod_deploy_infra.outputs.function_app_name }}
        package: './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        publish-profile: ${{ secrets.funcpublishprofile.outputs.profile }}

  prod_build_and_deploy_web_app:    
    runs-on: ubuntu-latest
    environment: production
    needs: [prod_deploy_infra, prod_build_and_deploy_function]
    name: Build and Deploy Web App
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: true
          lfs: false

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{ env.NODE_VERSION }}
    
      - name: 'Resolve Project Dependencies Using Npm'
        shell: bash
        env:
          VITE_API_URL: ${{ needs.prod_deploy_infra.outputs.function_app_url }}
        run: |
          pushd '${{ env.AZURE_WEB_APP_PACKAGE_PATH }}'
          npm install
          npm run build --if-present
          npm run test --if-present
          popd
    
      - name: Login via Az module
        uses: azure/login@v2.1.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
          enable-AzPSSession: true

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v3.0.1
        with: 
          app-name: ${{ needs.prod_deploy_infra.outputs.web_app_name }} # Replace with your app name
          package: '${{ env.AZURE_WEB_APP_PACKAGE_PATH }}/dist'

  prod_logic_app_build:
    runs-on: ubuntu-latest
    needs: [prod_build_and_deploy_function]
    name: Build Logic App
    steps: 
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Package logic
      run: (cd logic_app; mkdir -p ../output; zip -r ../output/logic_app.zip .)
    
    - name: Upload app zip package
      uses: actions/upload-artifact@v4.3.1
      with:
        name: logic_app
        path: ./output/
        retention-days: 1
  
  prod_logic_app_deploy: 
    name: Deploy Logic App
    runs-on: ubuntu-latest
    needs: [prod_deploy_infra, prod_logic_app_build]
    environment: 
      name: production
    steps: 
    - name: Checkout
      uses: actions/checkout@v4.1.1    
    
    - name: Login via Az module
      uses: azure/login@v2.1.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
        enable-AzPSSession: true
    - uses: actions/download-artifact@v4.1.2
      with:
        name: logic_app
        path: ./output/
  
    - name: Configure Logic App
      id: deploy_logic_app
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.RG_NAME }}
        template: ./infra/logic-config.bicep
        parameters: 'poc_name=${{ vars.POC_NAME }}'
        failOnStdErr: false
        deploymentName: 'config-logic-app-${{ github.run_id }}'
        scope: 'resourcegroup'

    - name: Get publish Profile
      id: publishprofile
      uses: azure/powershell@v2
      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{ vars.RG_NAME }} `
              -Name ${{ needs.prod_deploy_infra.outputs.logic_app_name }}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest

    - name: Deploy Workflows
      uses: Azure/functions-action@v1.5.1
      id: la
      with:
        app-name: ${{ needs.prod_deploy_infra.outputs.logic_app_name }}
        package: './output/logic_app.zip'
        publish-profile: ${{secrets.publishprofile.outputs.profile}}

    - name: Swap parameter files 
      id: params
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az functionapp deploy --resource-group ${{ vars.RG_NAME }} --name ${{ needs.prod_deploy_infra.outputs.logic_app_name }} --src-path ./logic_app/azure.parameters.json --type static --target-path parameters.json --restart true --clean true